### ISSUE TITLE
html head body

### ISSUE THREAD

**Issue by davidmarsprof** [monsieur-jonas/unserious-game#1]
Hello, pense à bien structurer toutes tes pages HTML avec un `<html>` un `<head>` et un `<body>`

**Comment by monsieur-jonas** [comment]
Avec un ? -------- Message original --------De : davidmarsprof <notifications@github.com>Date : mar. 13 oct. 2020 à 08:23À : monsieur-jonas/unserious-game <unserious-game@noreply.github.com>Cc : Subscribed <subscribed@noreply.github.com>Objet : [monsieur-jonas/unserious-game] html head body (#1)

Hello, pense à bien structurer toutes tes pages HTML avec un  un  et un

**Comment by davidmarsprof** [comment]
Salut regarde le message d'origine dans ton repos onglet "issues" ici... https://github.com/monsieur-jonas/unserious-game/issues/1 tu comprendras mieux ;)

**Comment by monsieur-jonas** [comment]
ah oui très bien je comprends ca ne s'affichait pas sur mon mail ^^'

**Comment by davidmarsprof** [comment]
Et oui car les mails c'est du HTML
